-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity c_grav is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    s_axis_video_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    s_axis_video_TVALID : IN STD_LOGIC;
    s_axis_video_TREADY : OUT STD_LOGIC;
    s_axis_video_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    s_axis_video_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    s_axis_video_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    hsize_in : IN STD_LOGIC_VECTOR (31 downto 0);
    vsize_in : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of c_grav is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "c_grav,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=1584,HLS_SYN_LUT=1685,HLS_VERSION=2019_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000100";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000001000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000010000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000100000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000001000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000010000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000100000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000001000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000010000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000100000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000001000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000010000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000100000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000001000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000010000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000100000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000001000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000010000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000100000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000001000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000010000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000100000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000001000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000010000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (38 downto 0) := "000000000000100000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (38 downto 0) := "000000000001000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (38 downto 0) := "000000000010000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (38 downto 0) := "000000000100000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (38 downto 0) := "000000001000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (38 downto 0) := "000000010000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (38 downto 0) := "000000100000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (38 downto 0) := "000001000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (38 downto 0) := "000010000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (38 downto 0) := "000100000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (38 downto 0) := "001000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (38 downto 0) := "010000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (38 downto 0) := "100000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_26 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100110";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_FFFFFFFB : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_64 : STD_LOGIC_VECTOR (7 downto 0) := "01100100";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (38 downto 0) := "000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal cgy_r : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    signal cgx_r : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    signal s_axis_video_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal icmp_ln24_reg_590 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln24_reg_590_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_147 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_0_reg_158 : STD_LOGIC_VECTOR (30 downto 0);
    signal nb_1_reg_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgx_1_reg_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgy_1_reg_194 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_0_reg_206 : STD_LOGIC_VECTOR (30 downto 0);
    signal val_assign_reg_218 : STD_LOGIC_VECTOR (7 downto 0);
    signal val_assign_1_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal val_assign_2_reg_246 : STD_LOGIC_VECTOR (7 downto 0);
    signal bound_fu_276_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_reg_578 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln26_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln26_reg_583 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln24_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln24_fu_296_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln24_reg_594 : STD_LOGIC_VECTOR (63 downto 0);
    signal cgy_r_load_reg_599 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln24_fu_308_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln24_reg_604 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal zext_ln24_fu_315_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_reg_609 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_1_fu_326_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln24_1_reg_614 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_keep_V_reg_620 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_strb_V_reg_625 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_user_V_reg_630 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_last_V_reg_635 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_id_V_reg_640 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_dest_V_reg_645 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixel_red_fu_358_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_red_reg_650 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_green_reg_658 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixel_blue_reg_666 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln34_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_reg_674 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_1_reg_678 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln34_2_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_423_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal j_reg_686 : STD_LOGIC_VECTOR (30 downto 0);
    signal cgx_fu_465_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgx_reg_691 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgy_fu_470_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgy_reg_696 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_fu_475_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_reg_701 : STD_LOGIC_VECTOR (31 downto 0);
    signal nb_2_fu_522_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgx_2_fu_529_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal cgy_2_fu_536_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln53_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_726 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_mux_indvar_flatten_phi_fu_151_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_i_0_phi_fu_162_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_j_0_phi_fu_210_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_mux_val_assign_phi_fu_221_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln34_fu_441_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_val_assign_reg_218 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_val_assign_reg_218 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_val_assign_1_phi_fu_235_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln34_1_fu_449_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_val_assign_1_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_val_assign_1_reg_232 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_val_assign_2_phi_fu_249_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln34_2_fu_457_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_val_assign_2_reg_246 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_val_assign_2_reg_246 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_555_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state41 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state41 : signal is "none";
    signal regslice_both_m_axis_video_V_data_V_U_apdone_blk : STD_LOGIC;
    signal grp_fu_549_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal bound_fu_276_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal bound_fu_276_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_fu_282_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln24_1_fu_302_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln24_1_fu_319_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln34_fu_382_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln34_1_fu_393_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln34_2_fu_405_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln26_fu_417_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln34_3_fu_430_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln34_3_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_1_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_2_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln40_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln40_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln40_1_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_549_ap_start : STD_LOGIC;
    signal grp_fu_549_ap_done : STD_LOGIC;
    signal grp_fu_549_ce : STD_LOGIC;
    signal grp_fu_555_ap_start : STD_LOGIC;
    signal grp_fu_555_ap_done : STD_LOGIC;
    signal grp_fu_555_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (38 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_s_axis_video_V_data_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDATA_int : STD_LOGIC_VECTOR (23 downto 0);
    signal s_axis_video_TVALID_int : STD_LOGIC;
    signal s_axis_video_TREADY_int : STD_LOGIC;
    signal regslice_both_s_axis_video_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TKEEP_int : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_s_axis_video_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TSTRB_int : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_s_axis_video_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_user_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TUSER_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_last_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_id_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TID_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_s_axis_video_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal s_axis_video_TDEST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_s_axis_video_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_axis_video_V_dest_V_U_ack_in : STD_LOGIC;
    signal m_axis_video_TDATA_int : STD_LOGIC_VECTOR (23 downto 0);
    signal m_axis_video_TVALID_int : STD_LOGIC;
    signal m_axis_video_TREADY_int : STD_LOGIC;
    signal regslice_both_m_axis_video_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_user_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_user_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_id_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_id_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_m_axis_video_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_m_axis_video_V_dest_V_U_vld_out : STD_LOGIC;
    signal bound_fu_276_p00 : STD_LOGIC_VECTOR (63 downto 0);
    signal bound_fu_276_p10 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_condition_280 : BOOLEAN;
    signal ap_condition_264 : BOOLEAN;

    component c_grav_udiv_32ns_bkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    c_grav_udiv_32ns_bkb_U1 : component c_grav_udiv_32ns_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_549_ap_start,
        done => grp_fu_549_ap_done,
        din0 => cgx_1_reg_182,
        din1 => nb_1_reg_170,
        ce => grp_fu_549_ce,
        dout => grp_fu_549_p2);

    c_grav_udiv_32ns_bkb_U2 : component c_grav_udiv_32ns_bkb
    generic map (
        ID => 1,
        NUM_STAGE => 36,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        start => grp_fu_555_ap_start,
        done => grp_fu_555_ap_done,
        din0 => cgy_1_reg_194,
        din1 => nb_1_reg_170,
        ce => grp_fu_555_ce,
        dout => grp_fu_555_p2);

    regslice_both_s_axis_video_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TDATA,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_data_V_U_ack_in,
        data_out => s_axis_video_TDATA_int,
        vld_out => s_axis_video_TVALID_int,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_data_V_U_apdone_blk);

    regslice_both_s_axis_video_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TKEEP,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_keep_V_U_ack_in,
        data_out => s_axis_video_TKEEP_int,
        vld_out => regslice_both_s_axis_video_V_keep_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_keep_V_U_apdone_blk);

    regslice_both_s_axis_video_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TSTRB,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_strb_V_U_ack_in,
        data_out => s_axis_video_TSTRB_int,
        vld_out => regslice_both_s_axis_video_V_strb_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_strb_V_U_apdone_blk);

    regslice_both_s_axis_video_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TUSER,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_user_V_U_ack_in,
        data_out => s_axis_video_TUSER_int,
        vld_out => regslice_both_s_axis_video_V_user_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_user_V_U_apdone_blk);

    regslice_both_s_axis_video_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TLAST,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_last_V_U_ack_in,
        data_out => s_axis_video_TLAST_int,
        vld_out => regslice_both_s_axis_video_V_last_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_last_V_U_apdone_blk);

    regslice_both_s_axis_video_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TID,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_id_V_U_ack_in,
        data_out => s_axis_video_TID_int,
        vld_out => regslice_both_s_axis_video_V_id_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_id_V_U_apdone_blk);

    regslice_both_s_axis_video_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_axis_video_TDEST,
        vld_in => s_axis_video_TVALID,
        ack_in => regslice_both_s_axis_video_V_dest_V_U_ack_in,
        data_out => s_axis_video_TDEST_int,
        vld_out => regslice_both_s_axis_video_V_dest_V_U_vld_out,
        ack_out => s_axis_video_TREADY_int,
        apdone_blk => regslice_both_s_axis_video_V_dest_V_U_apdone_blk);

    regslice_both_m_axis_video_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 24)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => m_axis_video_TDATA_int,
        vld_in => m_axis_video_TVALID_int,
        ack_in => m_axis_video_TREADY_int,
        data_out => m_axis_video_TDATA,
        vld_out => regslice_both_m_axis_video_V_data_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_data_V_U_apdone_blk);

    regslice_both_m_axis_video_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_keep_V_reg_620,
        vld_in => m_axis_video_TVALID_int,
        ack_in => regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy,
        data_out => m_axis_video_TKEEP,
        vld_out => regslice_both_m_axis_video_V_keep_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_keep_V_U_apdone_blk);

    regslice_both_m_axis_video_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 3)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_strb_V_reg_625,
        vld_in => m_axis_video_TVALID_int,
        ack_in => regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy,
        data_out => m_axis_video_TSTRB,
        vld_out => regslice_both_m_axis_video_V_strb_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_strb_V_U_apdone_blk);

    regslice_both_m_axis_video_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_user_V_reg_630,
        vld_in => m_axis_video_TVALID_int,
        ack_in => regslice_both_m_axis_video_V_user_V_U_ack_in_dummy,
        data_out => m_axis_video_TUSER,
        vld_out => regslice_both_m_axis_video_V_user_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_user_V_U_apdone_blk);

    regslice_both_m_axis_video_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_last_V_reg_635,
        vld_in => m_axis_video_TVALID_int,
        ack_in => regslice_both_m_axis_video_V_last_V_U_ack_in_dummy,
        data_out => m_axis_video_TLAST,
        vld_out => regslice_both_m_axis_video_V_last_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_last_V_U_apdone_blk);

    regslice_both_m_axis_video_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_id_V_reg_640,
        vld_in => m_axis_video_TVALID_int,
        ack_in => regslice_both_m_axis_video_V_id_V_U_ack_in_dummy,
        data_out => m_axis_video_TID,
        vld_out => regslice_both_m_axis_video_V_id_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_id_V_U_apdone_blk);

    regslice_both_m_axis_video_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => tmp_dest_V_reg_645,
        vld_in => m_axis_video_TVALID_int,
        ack_in => regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy,
        data_out => m_axis_video_TDEST,
        vld_out => regslice_both_m_axis_video_V_dest_V_U_vld_out,
        ack_out => m_axis_video_TREADY,
        apdone_blk => regslice_both_m_axis_video_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_val_assign_1_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_fu_387_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln34_1_fu_399_p2 = ap_const_lv1_0) and (icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_2_fu_411_p2 = ap_const_lv1_1) and (icmp_ln34_1_fu_399_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
                ap_phi_reg_pp0_iter1_val_assign_1_reg_232 <= s_axis_video_TDATA_int(15 downto 8);
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_phi_reg_pp0_iter1_val_assign_1_reg_232 <= ap_phi_reg_pp0_iter0_val_assign_1_reg_232;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_val_assign_2_reg_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_fu_387_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln34_1_fu_399_p2 = ap_const_lv1_0) and (icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_2_fu_411_p2 = ap_const_lv1_1) and (icmp_ln34_1_fu_399_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
                ap_phi_reg_pp0_iter1_val_assign_2_reg_246 <= s_axis_video_TDATA_int(23 downto 16);
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_phi_reg_pp0_iter1_val_assign_2_reg_246 <= ap_phi_reg_pp0_iter0_val_assign_2_reg_246;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_val_assign_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_fu_387_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln34_1_fu_399_p2 = ap_const_lv1_0) and (icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)) or ((icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_2_fu_411_p2 = ap_const_lv1_1) and (icmp_ln34_1_fu_399_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001)))) then 
                ap_phi_reg_pp0_iter1_val_assign_reg_218 <= pixel_red_fu_358_p1;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_phi_reg_pp0_iter1_val_assign_reg_218 <= ap_phi_reg_pp0_iter0_val_assign_reg_218;
            end if; 
        end if;
    end process;

    cgx_1_reg_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                cgx_1_reg_182 <= cgx_2_fu_529_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                cgx_1_reg_182 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    cgy_1_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                cgy_1_reg_194 <= cgy_2_fu_536_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                cgy_1_reg_194 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_reg_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                i_0_reg_158 <= select_ln24_reg_604;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_158 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_147 <= add_ln24_reg_594;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_147 <= ap_const_lv64_0;
            end if; 
        end if;
    end process;

    j_0_reg_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                j_0_reg_206 <= j_reg_686;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_0_reg_206 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    nb_1_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                nb_1_reg_170 <= nb_2_fu_522_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                nb_1_reg_170 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    val_assign_1_reg_232_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_264)) then
                if ((ap_const_boolean_1 = ap_condition_280)) then 
                    val_assign_1_reg_232 <= select_ln34_1_fu_449_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    val_assign_1_reg_232 <= ap_phi_reg_pp0_iter1_val_assign_1_reg_232;
                end if;
            end if; 
        end if;
    end process;

    val_assign_2_reg_246_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_264)) then
                if ((ap_const_boolean_1 = ap_condition_280)) then 
                    val_assign_2_reg_246 <= select_ln34_2_fu_457_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    val_assign_2_reg_246 <= ap_phi_reg_pp0_iter1_val_assign_2_reg_246;
                end if;
            end if; 
        end if;
    end process;

    val_assign_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_264)) then
                if ((ap_const_boolean_1 = ap_condition_280)) then 
                    val_assign_reg_218 <= select_ln34_fu_441_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    val_assign_reg_218 <= ap_phi_reg_pp0_iter1_val_assign_reg_218;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln24_reg_594 <= add_ln24_fu_296_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                bound_reg_578 <= bound_fu_276_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_726 = ap_const_lv1_0) and (regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state41))) then
                cgx_r <= grp_fu_549_p2;
                cgy_r <= grp_fu_555_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cgx_reg_691 <= cgx_fu_465_p2;
                cgy_reg_696 <= cgy_fu_470_p2;
                nb_reg_701 <= nb_fu_475_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_fu_291_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                cgy_r_load_reg_599 <= cgy_r;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln24_reg_590 <= icmp_ln24_fu_291_p2;
                icmp_ln24_reg_590_pp0_iter1_reg <= icmp_ln24_reg_590;
                icmp_ln26_reg_583 <= icmp_ln26_fu_286_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                icmp_ln34_1_reg_678 <= icmp_ln34_1_fu_399_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln34_fu_387_p2 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_1_fu_399_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                icmp_ln34_2_reg_682 <= icmp_ln34_2_fu_411_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                icmp_ln34_reg_674 <= icmp_ln34_fu_387_p2;
                pixel_blue_reg_666 <= s_axis_video_TDATA_int(23 downto 16);
                pixel_green_reg_658 <= s_axis_video_TDATA_int(15 downto 8);
                pixel_red_reg_650 <= pixel_red_fu_358_p1;
                tmp_dest_V_reg_645 <= s_axis_video_TDEST_int;
                tmp_id_V_reg_640 <= s_axis_video_TID_int;
                tmp_keep_V_reg_620 <= s_axis_video_TKEEP_int;
                tmp_last_V_reg_635 <= s_axis_video_TLAST_int;
                tmp_strb_V_reg_625 <= s_axis_video_TSTRB_int;
                tmp_user_V_reg_630 <= s_axis_video_TUSER_int;
                    zext_ln24_1_reg_614(30 downto 0) <= zext_ln24_1_fu_326_p1(30 downto 0);
                    zext_ln24_reg_609(30 downto 0) <= zext_ln24_fu_315_p1(30 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                icmp_ln53_reg_726 <= icmp_ln53_fu_543_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                j_reg_686 <= j_fu_423_p3;
                select_ln24_reg_604 <= select_ln24_fu_308_p3;
            end if;
        end if;
    end process;
    zext_ln24_reg_609(31) <= '0';
    zext_ln24_1_reg_614(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, icmp_ln24_fu_291_p2, icmp_ln53_fu_543_p2, ap_CS_fsm_state6, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone, ap_CS_fsm_state41, regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln24_fu_291_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln24_fu_291_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln53_fu_543_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state41;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state41))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state41;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln24_1_fu_302_p2 <= std_logic_vector(unsigned(ap_const_lv31_1) + unsigned(ap_phi_mux_i_0_phi_fu_162_p4));
    add_ln24_fu_296_p2 <= std_logic_vector(unsigned(ap_phi_mux_indvar_flatten_phi_fu_151_p4) + unsigned(ap_const_lv64_1));
    add_ln26_fu_417_p2 <= std_logic_vector(unsigned(j_0_reg_206) + unsigned(ap_const_lv31_1));
    add_ln34_1_fu_393_p2 <= std_logic_vector(unsigned(cgy_r) + unsigned(ap_const_lv32_5));
    add_ln34_2_fu_405_p2 <= std_logic_vector(unsigned(cgx_r) + unsigned(ap_const_lv32_FFFFFFFB));
    add_ln34_3_fu_430_p2 <= std_logic_vector(unsigned(cgx_r) + unsigned(ap_const_lv32_5));
    add_ln34_fu_382_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFB) + signed(cgy_r_load_reg_599));
    and_ln40_1_fu_516_p2 <= (icmp_ln40_fu_492_p2 and and_ln40_fu_510_p2);
    and_ln40_fu_510_p2 <= (icmp_ln40_2_fu_504_p2 and icmp_ln40_1_fu_498_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state41 <= ap_CS_fsm(38);
    ap_CS_fsm_state6 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_boolean_1 = ap_block_state4_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state4_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_boolean_1 = ap_block_state4_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln24_reg_590, ap_enable_reg_pp0_iter1, ap_block_state5_io, s_axis_video_TVALID_int)
    begin
                ap_block_pp0_stage1_11001 <= (((icmp_ln24_reg_590 = ap_const_lv1_0) and (s_axis_video_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln24_reg_590, ap_enable_reg_pp0_iter1, ap_block_state5_io, s_axis_video_TVALID_int)
    begin
                ap_block_pp0_stage1_subdone <= (((icmp_ln24_reg_590 = ap_const_lv1_0) and (s_axis_video_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)) or ((ap_const_boolean_1 = ap_block_state5_io) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage1_iter0_assign_proc : process(icmp_ln24_reg_590, s_axis_video_TVALID_int)
    begin
                ap_block_state3_pp0_stage1_iter0 <= ((icmp_ln24_reg_590 = ap_const_lv1_0) and (s_axis_video_TVALID_int = ap_const_logic_0));
    end process;


    ap_block_state4_io_assign_proc : process(icmp_ln24_reg_590, m_axis_video_TREADY_int)
    begin
                ap_block_state4_io <= ((icmp_ln24_reg_590 = ap_const_lv1_0) and (m_axis_video_TREADY_int = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_io_assign_proc : process(icmp_ln24_reg_590_pp0_iter1_reg, m_axis_video_TREADY_int)
    begin
                ap_block_state5_io <= ((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (m_axis_video_TREADY_int = ap_const_logic_0));
    end process;

        ap_block_state5_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_264_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
                ap_condition_264 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_280_assign_proc : process(icmp_ln24_reg_590, icmp_ln34_reg_674, icmp_ln34_1_reg_678, icmp_ln34_2_reg_682)
    begin
                ap_condition_280 <= ((icmp_ln34_2_reg_682 = ap_const_lv1_0) and (icmp_ln34_reg_674 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_1_reg_678 = ap_const_lv1_1));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln24_fu_291_p2)
    begin
        if ((icmp_ln24_fu_291_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state41, regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state41))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_i_0_phi_fu_162_p4_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, ap_enable_reg_pp0_iter1, icmp_ln24_reg_590_pp0_iter1_reg, i_0_reg_158, select_ln24_reg_604)
    begin
        if (((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            ap_phi_mux_i_0_phi_fu_162_p4 <= select_ln24_reg_604;
        else 
            ap_phi_mux_i_0_phi_fu_162_p4 <= i_0_reg_158;
        end if; 
    end process;


    ap_phi_mux_indvar_flatten_phi_fu_151_p4_assign_proc : process(icmp_ln24_reg_590, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, indvar_flatten_reg_147, add_ln24_reg_594)
    begin
        if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_indvar_flatten_phi_fu_151_p4 <= add_ln24_reg_594;
        else 
            ap_phi_mux_indvar_flatten_phi_fu_151_p4 <= indvar_flatten_reg_147;
        end if; 
    end process;


    ap_phi_mux_j_0_phi_fu_210_p4_assign_proc : process(icmp_ln24_reg_590, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, j_0_reg_206, j_reg_686)
    begin
        if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_j_0_phi_fu_210_p4 <= j_reg_686;
        else 
            ap_phi_mux_j_0_phi_fu_210_p4 <= j_0_reg_206;
        end if; 
    end process;


    ap_phi_mux_val_assign_1_phi_fu_235_p8_assign_proc : process(icmp_ln24_reg_590, icmp_ln34_reg_674, icmp_ln34_1_reg_678, icmp_ln34_2_reg_682, select_ln34_1_fu_449_p3, ap_phi_reg_pp0_iter1_val_assign_1_reg_232)
    begin
        if (((icmp_ln34_2_reg_682 = ap_const_lv1_0) and (icmp_ln34_reg_674 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_1_reg_678 = ap_const_lv1_1))) then 
            ap_phi_mux_val_assign_1_phi_fu_235_p8 <= select_ln34_1_fu_449_p3;
        else 
            ap_phi_mux_val_assign_1_phi_fu_235_p8 <= ap_phi_reg_pp0_iter1_val_assign_1_reg_232;
        end if; 
    end process;


    ap_phi_mux_val_assign_2_phi_fu_249_p8_assign_proc : process(icmp_ln24_reg_590, icmp_ln34_reg_674, icmp_ln34_1_reg_678, icmp_ln34_2_reg_682, select_ln34_2_fu_457_p3, ap_phi_reg_pp0_iter1_val_assign_2_reg_246)
    begin
        if (((icmp_ln34_2_reg_682 = ap_const_lv1_0) and (icmp_ln34_reg_674 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_1_reg_678 = ap_const_lv1_1))) then 
            ap_phi_mux_val_assign_2_phi_fu_249_p8 <= select_ln34_2_fu_457_p3;
        else 
            ap_phi_mux_val_assign_2_phi_fu_249_p8 <= ap_phi_reg_pp0_iter1_val_assign_2_reg_246;
        end if; 
    end process;


    ap_phi_mux_val_assign_phi_fu_221_p8_assign_proc : process(icmp_ln24_reg_590, icmp_ln34_reg_674, icmp_ln34_1_reg_678, icmp_ln34_2_reg_682, select_ln34_fu_441_p3, ap_phi_reg_pp0_iter1_val_assign_reg_218)
    begin
        if (((icmp_ln34_2_reg_682 = ap_const_lv1_0) and (icmp_ln34_reg_674 = ap_const_lv1_0) and (icmp_ln24_reg_590 = ap_const_lv1_0) and (icmp_ln34_1_reg_678 = ap_const_lv1_1))) then 
            ap_phi_mux_val_assign_phi_fu_221_p8 <= select_ln34_fu_441_p3;
        else 
            ap_phi_mux_val_assign_phi_fu_221_p8 <= ap_phi_reg_pp0_iter1_val_assign_reg_218;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_val_assign_1_reg_232 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_val_assign_2_reg_246 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_val_assign_reg_218 <= "XXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state41, regslice_both_m_axis_video_V_data_V_U_apdone_blk)
    begin
        if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state41))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bound_fu_276_p0 <= bound_fu_276_p00(32 - 1 downto 0);
    bound_fu_276_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hsize_in),64));
    bound_fu_276_p1 <= bound_fu_276_p10(32 - 1 downto 0);
    bound_fu_276_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vsize_in),64));
    bound_fu_276_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bound_fu_276_p0) * unsigned(bound_fu_276_p1), 64));
    cgx_2_fu_529_p3 <= 
        cgx_reg_691 when (and_ln40_1_fu_516_p2(0) = '1') else 
        cgx_1_reg_182;
    cgx_fu_465_p2 <= std_logic_vector(unsigned(zext_ln24_1_reg_614) + unsigned(cgx_1_reg_182));
    cgy_2_fu_536_p3 <= 
        cgy_reg_696 when (and_ln40_1_fu_516_p2(0) = '1') else 
        cgy_1_reg_194;
    cgy_fu_470_p2 <= std_logic_vector(unsigned(cgy_1_reg_194) + unsigned(zext_ln24_reg_609));

    grp_fu_549_ap_start_assign_proc : process(icmp_ln53_fu_543_p2, ap_CS_fsm_state6)
    begin
        if (((icmp_ln53_fu_543_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_fu_549_ap_start <= ap_const_logic_1;
        else 
            grp_fu_549_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_549_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) or (ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_549_ce <= ap_const_logic_0;
        else 
            grp_fu_549_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_555_ap_start_assign_proc : process(icmp_ln53_fu_543_p2, ap_CS_fsm_state6)
    begin
        if (((icmp_ln53_fu_543_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            grp_fu_555_ap_start <= ap_const_logic_1;
        else 
            grp_fu_555_ap_start <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_555_ce_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_pp0_stage1, ap_CS_fsm_pp0_stage0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) or (ap_const_logic_1 = ap_CS_fsm_state1) or (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_fu_555_ce <= ap_const_logic_0;
        else 
            grp_fu_555_ce <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln24_fu_291_p2 <= "1" when (ap_phi_mux_indvar_flatten_phi_fu_151_p4 = bound_reg_578) else "0";
    icmp_ln26_fu_286_p2 <= "1" when (signed(zext_ln26_fu_282_p1) < signed(hsize_in)) else "0";
    icmp_ln34_1_fu_399_p2 <= "1" when (signed(zext_ln24_fu_315_p1) < signed(add_ln34_1_fu_393_p2)) else "0";
    icmp_ln34_2_fu_411_p2 <= "1" when (signed(zext_ln24_1_fu_326_p1) < signed(add_ln34_2_fu_405_p2)) else "0";
    icmp_ln34_3_fu_436_p2 <= "1" when (signed(zext_ln24_1_reg_614) < signed(add_ln34_3_fu_430_p2)) else "0";
    icmp_ln34_fu_387_p2 <= "1" when (signed(zext_ln24_fu_315_p1) < signed(add_ln34_fu_382_p2)) else "0";
    icmp_ln40_1_fu_498_p2 <= "1" when (unsigned(val_assign_1_reg_232) < unsigned(ap_const_lv8_64)) else "0";
    icmp_ln40_2_fu_504_p2 <= "1" when (unsigned(val_assign_2_reg_246) < unsigned(ap_const_lv8_64)) else "0";
    icmp_ln40_fu_492_p2 <= "1" when (unsigned(val_assign_reg_218) < unsigned(ap_const_lv8_64)) else "0";
    icmp_ln53_fu_543_p2 <= "1" when (nb_1_reg_170 = ap_const_lv32_0) else "0";
    j_fu_423_p3 <= 
        add_ln26_fu_417_p2 when (icmp_ln26_reg_583(0) = '1') else 
        ap_const_lv31_1;

    m_axis_video_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1, icmp_ln24_reg_590, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln24_reg_590_pp0_iter1_reg, m_axis_video_TREADY_int)
    begin
        if ((((icmp_ln24_reg_590_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            m_axis_video_TDATA_blk_n <= m_axis_video_TREADY_int;
        else 
            m_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_video_TDATA_int <= ((ap_phi_mux_val_assign_2_phi_fu_249_p8 & ap_phi_mux_val_assign_1_phi_fu_235_p8) & ap_phi_mux_val_assign_phi_fu_221_p8);
    m_axis_video_TVALID <= regslice_both_m_axis_video_V_data_V_U_vld_out;

    m_axis_video_TVALID_int_assign_proc : process(icmp_ln24_reg_590, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axis_video_TVALID_int <= ap_const_logic_1;
        else 
            m_axis_video_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    nb_2_fu_522_p3 <= 
        nb_reg_701 when (and_ln40_1_fu_516_p2(0) = '1') else 
        nb_1_reg_170;
    nb_fu_475_p2 <= std_logic_vector(unsigned(nb_1_reg_170) + unsigned(ap_const_lv32_1));
    pixel_red_fu_358_p1 <= s_axis_video_TDATA_int(8 - 1 downto 0);

    s_axis_video_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, icmp_ln24_reg_590, s_axis_video_TVALID_int)
    begin
        if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            s_axis_video_TDATA_blk_n <= s_axis_video_TVALID_int;
        else 
            s_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s_axis_video_TREADY_assign_proc : process(s_axis_video_TVALID, regslice_both_s_axis_video_V_data_V_U_ack_in)
    begin
        if (((regslice_both_s_axis_video_V_data_V_U_ack_in = ap_const_logic_1) and (s_axis_video_TVALID = ap_const_logic_1))) then 
            s_axis_video_TREADY <= ap_const_logic_1;
        else 
            s_axis_video_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    s_axis_video_TREADY_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, icmp_ln24_reg_590, ap_block_pp0_stage1_11001)
    begin
        if (((icmp_ln24_reg_590 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
            s_axis_video_TREADY_int <= ap_const_logic_1;
        else 
            s_axis_video_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

    select_ln24_1_fu_319_p3 <= 
        j_0_reg_206 when (icmp_ln26_reg_583(0) = '1') else 
        ap_const_lv31_0;
    select_ln24_fu_308_p3 <= 
        ap_phi_mux_i_0_phi_fu_162_p4 when (icmp_ln26_reg_583(0) = '1') else 
        add_ln24_1_fu_302_p2;
    select_ln34_1_fu_449_p3 <= 
        ap_const_lv8_FF when (icmp_ln34_3_fu_436_p2(0) = '1') else 
        pixel_green_reg_658;
    select_ln34_2_fu_457_p3 <= 
        ap_const_lv8_FF when (icmp_ln34_3_fu_436_p2(0) = '1') else 
        pixel_blue_reg_666;
    select_ln34_fu_441_p3 <= 
        ap_const_lv8_FF when (icmp_ln34_3_fu_436_p2(0) = '1') else 
        pixel_red_reg_650;
    zext_ln24_1_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_1_fu_319_p3),32));
    zext_ln24_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln24_fu_308_p3),32));
    zext_ln26_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_j_0_phi_fu_210_p4),32));
end behav;
