# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/PFE/Pcam_base/Pcam_base.srcs/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0.xci
# IP: The module: 'system_s00_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/PFE/Pcam_base/Pcam_base.srcs/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/PFE/Pcam_base/Pcam_base.srcs/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/PFE/Pcam_base/Pcam_base.srcs/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0.xci
# IP: The module: 'system_s00_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/PFE/Pcam_base/Pcam_base.srcs/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: f:/PFE/Pcam_base/Pcam_base.srcs/sources_1/bd/system/ip/system_s00_regslice_0/system_s00_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
