# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zed_board.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlslice_1_0/design_2_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_1_0 || ORIG_REF_NAME==design_2_xlslice_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_1_0/design_2_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_1_0 || ORIG_REF_NAME==design_2_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_v_tc_0_0/design_2_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_v_tc_0_0 || ORIG_REF_NAME==design_2_v_tc_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_v_axi4s_vid_out_0_0/design_2_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_2_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_2_0/design_2_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_2_0 || ORIG_REF_NAME==design_2_xlconstant_2_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconcat_0_0/design_2_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_0 || ORIG_REF_NAME==design_2_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xlconstant_5_0/design_2_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_5_0 || ORIG_REF_NAME==design_2_xlconstant_5_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_i2c_sender_adv7511_0_0/design_2_i2c_sender_adv7511_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_i2c_sender_adv7511_0_0 || ORIG_REF_NAME==design_2_i2c_sender_adv7511_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==design_2_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_smartconnect_0_0/design_2_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_smartconnect_0_0 || ORIG_REF_NAME==design_2_smartconnect_0_0} -quiet] -quiet

# Block Designs: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/bd_0c5c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_0/bd_0c5c_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_2/bd_0c5c_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_3/bd_0c5c_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_4/bd_0c5c_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_5/bd_0c5c_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_6/bd_0c5c_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_7/bd_0c5c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_8/bd_0c5c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_9/bd_0c5c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_10/bd_0c5c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_11/bd_0c5c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_12/bd_0c5c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_13/bd_0c5c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_14/bd_0c5c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_15/bd_0c5c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_16/bd_0c5c_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_17/bd_0c5c_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_18/bd_0c5c_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_19/bd_0c5c_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_20/bd_0c5c_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_21/bd_0c5c_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_22/bd_0c5c_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_23/bd_0c5c_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_24/bd_0c5c_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_25/bd_0c5c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_26/bd_0c5c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_27/bd_0c5c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_28/bd_0c5c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_29/bd_0c5c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_30/bd_0c5c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_31/bd_0c5c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_32/bd_0c5c_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_33/bd_0c5c_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_34/bd_0c5c_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_35/bd_0c5c_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_36/bd_0c5c_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_37/bd_0c5c_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_38/bd_0c5c_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_39/bd_0c5c_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_40/bd_0c5c_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_41/bd_0c5c_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_42/bd_0c5c_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_43/bd_0c5c_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_44/bd_0c5c_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_45/bd_0c5c_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_46/bd_0c5c_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_47/bd_0c5c_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_48/bd_0c5c_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_49/bd_0c5c_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_50/bd_0c5c_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_51/bd_0c5c_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_52/bd_0c5c_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_53/bd_0c5c_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_54/bd_0c5c_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_55/bd_0c5c_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_56/bd_0c5c_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_57/bd_0c5c_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_58/bd_0c5c_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_59/bd_0c5c_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_60/bd_0c5c_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_61/bd_0c5c_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_62/bd_0c5c_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_63/bd_0c5c_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_64/bd_0c5c_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_65/bd_0c5c_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_66/bd_0c5c_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_67/bd_0c5c_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_68/bd_0c5c_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_69/bd_0c5c_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_70/bd_0c5c_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_71/bd_0c5c_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_72/bd_0c5c_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_73/bd_0c5c_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_2/ip/design_2_im_load_mm_0_0/design_2_im_load_mm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_im_load_mm_0_0 || ORIG_REF_NAME==design_2_im_load_mm_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_incrust_0_0/design_2_incrust_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_incrust_0_0 || ORIG_REF_NAME==design_2_incrust_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_switch_value_0_0/design_2_switch_value_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_switch_value_0_0 || ORIG_REF_NAME==design_2_switch_value_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_incust_bar_0_0/design_2_incust_bar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_incust_bar_0_0 || ORIG_REF_NAME==design_2_incust_bar_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_incrust_1_0/design_2_incrust_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_incrust_1_0 || ORIG_REF_NAME==design_2_incrust_1_0} -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_v_tc_0_0/design_2_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_v_tc_0_0 || ORIG_REF_NAME==design_2_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_v_tc_0_0/design_2_v_tc_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_v_axi4s_vid_out_0_0/design_2_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==design_2_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_v_axi4s_vid_out_0_0/design_2_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_bram_ctrl_0_0/design_2_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_axi_bram_ctrl_0_bram_0/design_2_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_1/bd_0c5c_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_2/bd_0c5c_arsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_3/bd_0c5c_rsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_4/bd_0c5c_awsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_5/bd_0c5c_wsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_6/bd_0c5c_bsw_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_10/bd_0c5c_s00a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_11/bd_0c5c_sarn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_12/bd_0c5c_srn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_13/bd_0c5c_sawn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_14/bd_0c5c_swn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_15/bd_0c5c_sbn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_19/bd_0c5c_s01a2s_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_20/bd_0c5c_sarn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_21/bd_0c5c_srn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_22/bd_0c5c_sawn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_23/bd_0c5c_swn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_24/bd_0c5c_sbn_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_25/bd_0c5c_m00s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_26/bd_0c5c_m00arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_27/bd_0c5c_m00rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_28/bd_0c5c_m00awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_29/bd_0c5c_m00wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_30/bd_0c5c_m00bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_32/bd_0c5c_m01s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_33/bd_0c5c_m01arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_34/bd_0c5c_m01rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_35/bd_0c5c_m01awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_36/bd_0c5c_m01wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_37/bd_0c5c_m01bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_39/bd_0c5c_m02s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_40/bd_0c5c_m02arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_41/bd_0c5c_m02rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_42/bd_0c5c_m02awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_43/bd_0c5c_m02wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_44/bd_0c5c_m02bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_46/bd_0c5c_m03s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_47/bd_0c5c_m03arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_48/bd_0c5c_m03rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_49/bd_0c5c_m03awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_50/bd_0c5c_m03wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_51/bd_0c5c_m03bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_53/bd_0c5c_m04s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_54/bd_0c5c_m04arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_55/bd_0c5c_m04rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_56/bd_0c5c_m04awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_57/bd_0c5c_m04wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_58/bd_0c5c_m04bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_60/bd_0c5c_m05s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_61/bd_0c5c_m05arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_62/bd_0c5c_m05rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_63/bd_0c5c_m05awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_64/bd_0c5c_m05wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_65/bd_0c5c_m05bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_67/bd_0c5c_m06s2a_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_68/bd_0c5c_m06arn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_69/bd_0c5c_m06rn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_70/bd_0c5c_m06awn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_71/bd_0c5c_m06wn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/bd_0/ip/ip_72/bd_0c5c_m06bn_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_smartconnect_0_0/ooc.xdc

# XDC: bd/design_2/ip/design_2_im_load_mm_0_0/constraints/im_load_mm_ooc.xdc

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_0 || ORIG_REF_NAME==design_2_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_0/design_2_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_proc_sys_reset_0_1 || ORIG_REF_NAME==design_2_proc_sys_reset_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_proc_sys_reset_0_1/design_2_proc_sys_reset_0_1_ooc.xdc

# XDC: bd/design_2/ip/design_2_incrust_0_0/constraints/incrust_ooc.xdc

# XDC: bd/design_2/ip/design_2_processing_system7_0_0/design_2_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_2_processing_system7_0_0 || ORIG_REF_NAME==design_2_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_2/ip/design_2_incust_bar_0_0/constraints/incust_bar_ooc.xdc

# XDC: bd/design_2/ip/design_2_incrust_1_0/constraints/incrust_ooc.xdc

# XDC: bd/design_2/design_2_ooc.xdc
